name: Bundle analysis

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  run-bundle-analysis:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_URI: ${{ secrets.NEXT_PUBLIC_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Analyze bundle sizes
        uses: transferwise/actions-next-bundle-analyzer@master
        with:
          workflow-id: CI.yml
          base-branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_URI: ${{ secrets.NEXT_PUBLIC_URI }}
